blank_issues_enabled: false
contact_links:
  - name: 게임 커뮤니티
    url: https://github.com/SoMa-Team/Trieyes-Trial-of-gods/discussions
    about: 게임에 대한 일반적인 토론이나 질문은 여기서 해주세요
  - name: 개발자 문서
    url: https://github.com/SoMa-Team/Trieyes-Trial-of-gods/wiki
    about: 개발 가이드라인과 문서를 확인하세요 